meta:
    site_title: "念愿的博客"
    site_subtitle: "学习，贵在坚持！"
    site_language: "zh-cn"
#   absolute_baseurl: http://www.cailiwei.com.cn/
    absolute_baseurl: /
    books_baseurl: /books
    movies_baseurl: /movies
    images_baseurl: /images/

    author:
        full_name: Cai Liwei
        short_name: Levy
        name: 念愿
        email: cailiwei712@163.com

url: http://blog.cailiwei.com.cn/

markdown: kramdown

# how many items should be displayed per page.
paginate: 5
paginate_path: "blog/page:num"

permalink: /blog/:year/:month/:day/:title
# /blog/2009/04/29/slap-chop/index.html
# permalink: /:month-:day-:year/:title.html 
#            /04-29-2009/slap-chop.html

disqus_short_name: clw.story

css:
   - /css/style.css
