site_title: "念愿驿站"
site_subtitle: "自由分享,提高认知！"
site_language: "zh-cn"

author: "蔡立维(Levy)"
email: cailiwei712@163.com

url: http://blog.cailiwei.com.cn
baseurl: http://blog.cailiwei.com.cn

markdown: kramdown

# how many items should be displayed per page.
paginate: 5
paginate_path: "blog/page:num"

# < ----------- add by liwei.cai ------------------ >

# 博客输出url格式
permalink: /blog/:year/:month/:day/:title
# /blog/2009/04/29/slap-chop/index.html
# permalink: /:month-:day-:year/:title.html
#            /04-29-2009/slap-chop.html

# 代码高亮设置
pygments: true

# 保持Jekyll运行，查看你的项目目录的改变并随时生成网站
# auto: true

# jekyll 忽略被包含的文件和目录
# exclude: "temp"

disqus_short_name: levycai

css:
   - /css/style.css
