meta:
    site_title: "念愿的博客"
    site_subtitle: "学习，贵在坚持！"
    site_language: "zh-cn"
    absolute_baseurl: http://cailiwei.github.com/yuan/
    domain: github.com
    author:
        full_name: Cai Liwei
        short_name: Levy
        name: 念愿
        email: cailiwei712@163.com

url: http://cailiwei.github.com/yuan/

# baseurl: /base

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /blog/:year/:month/:day/:title

disqus_short_name: clw.story

      
css:
    - /css/screen.css

